# -*- coding: utf-8 -*-
"""8thclss0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/shah4702/768409c3a3b79658c43acd8d24ef61de/8thclss0.ipynb
"""

n = 10
if n % 2 == 0:
  print("Even")
else:
  print("Odd")

for i in range(1, 11):
  if i % 2 == 0:
    print(i, "is even")
  else:
    print(i, "is odd")

for i in range(1, 11):
  if i % 2 == 0:
    print(i, "is even")

for x in range(n):
  if x % 2 == 0:
    print(x, "end=")

for x in range(n):
  if x % 2 == 1:
    print(x, "end=")

X=0
for x in range(n):
  if x % 2 == 0:
    print(x, "end=")
  else:
    continue

#Exanple: wguke kiop and continue statement
#print("print old number from 1 to 10")
i = 0
while i < 10:
  i += 1
  if i % 2 == 0:
    continue
  print(i)

i = -1
while i < 10:
  i += 1
  if i % 2 == 1:
    continue
  print(i)

n = int(input("Enter a number: "))
i = -1
while i < 10 :
  i += 1
  if i % 2 == 1:
    continue
  print(i, end=" ")

n = int(input("Enter a number:"))
i = -1
while i < 10:
  i += 1
  if i % 2 == 1:
    continue
  print(i, end=" ")

def fnReverseNumber():
  n = int(input("Enter a number"))
  l = len(str(n))
  for i in range(l):
    x = n % 10
    y = int(n/10)
    print(x, end=" ")
    n = y
fnReverseNumber()

n = input("Enter a number: ")
a, b = 0, 1
print(a)
for i in range(n):

#python 3.14 uper version saty in bulding function

#take an email addresss and split domain name and user name

email = input("Enter your email address: ")
user_name, domain_name = email.split("@")
print(user_name)
print(domain_name)

email = input("Enter your email address: ")
length = len(email)
loc = email.find("@")
user_name = email[:loc]
domain_name = email[loc+1:]
print(user_name)
print(domain_name)

