# -*- coding: utf-8 -*-
"""9thclss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7V2SfBhZeJJNv7ofIQb8g-FKi56PBfS
"""

def main_menu():
  print("MAIN MENU")
  print("1. String Operation")
  print("2. Number Operation")
  print("3. EXIT")


def main():
  while (True):
    main_menu()
    choice = input('\nEnter choice(1, 2 or 3): ')
    if choice == '1':
      print("\nThank you for choosing string operation")
    elif choice == '2':
      print('\nThank you for choosing number operation.')
    elif choice == '3':
      print('\nThanks for using Switch Statements')
      break
    else:
      print('\nInvalid input!!!')
main()

